export const metadata = {
  title: 'Next.js',
    absolute: 'dashboard-app.com',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}